#!/bin/bash


#===============================================================================
#
#  Cell BLAST
#
#===============================================================================
./sankey.py -t ../Datasets/data/Young/data.h5//obs/cell_ontology_class ../Datasets/data/Wu_human/data.h5//obs/cell_ontology_class ../Datasets/data/Zheng_subsample/data.h5//obs/cell_ontology_class ../Datasets/data/Philippeos/data.h5//obs/cell_ontology_class -p ../Results/Cell_BLAST/Baron_human+Xin_2016+Lawlor/seurat_genes/dim_10_rmbatch_0.01/blast_0/Young.h5//prediction/0.05 ../Results/Cell_BLAST/Baron_human+Xin_2016+Lawlor/seurat_genes/dim_10_rmbatch_0.01/blast_0/Wu_human.h5//prediction/0.05 ../Results/Cell_BLAST/Baron_human+Xin_2016+Lawlor/seurat_genes/dim_10_rmbatch_0.01/blast_0/Zheng_subsample.h5//prediction/0.05 ../Results/Cell_BLAST/Baron_human+Xin_2016+Lawlor/seurat_genes/dim_10_rmbatch_0.01/blast_0/Philippeos.h5//prediction/0.05 -o ../Results/Cell_BLAST/Baron_human+Xin_2016+Lawlor/seurat_genes/dim_10_rmbatch_0.01/blast_0/nc.pdf --clean-true --tint-cutoff 5 --width 600 --title "Pancreas negative control"
./sankey.py -t ../Datasets/data/Muraro/data.h5//obs/cell_ontology_class ../Datasets/data/Segerstolpe/data.h5//obs/cell_ontology_class ../Datasets/data/Enge/data.h5//obs/cell_ontology_class -p ../Results/Cell_BLAST/Baron_human+Xin_2016+Lawlor/seurat_genes/dim_10_rmbatch_0.01/blast_0/Muraro.h5//prediction/0.05 ../Results/Cell_BLAST/Baron_human+Xin_2016+Lawlor/seurat_genes/dim_10_rmbatch_0.01/blast_0/Segerstolpe.h5//prediction/0.05 ../Results/Cell_BLAST/Baron_human+Xin_2016+Lawlor/seurat_genes/dim_10_rmbatch_0.01/blast_0/Enge.h5//prediction/0.05 -o ../Results/Cell_BLAST/Baron_human+Xin_2016+Lawlor/seurat_genes/dim_10_rmbatch_0.01/blast_0/pc.pdf --clean-true --tint-cutoff 5 --width 600 --title "Pancreas positive control"

./sankey.py -t ../Datasets/data/Baron_mouse/data.h5//obs/cell_ontology_class ../Datasets/data/Park/data.h5//obs/cell_ontology_class ../Datasets/data/Bach/data.h5//obs/cell_ontology_class ../Datasets/data/Macosko/data.h5//obs/cell_ontology_class -p ../Results/Cell_BLAST/Montoro_10x/seurat_genes/dim_10/blast_0/Baron_mouse.h5//prediction/0.05 ../Results/Cell_BLAST/Montoro_10x/seurat_genes/dim_10/blast_0/Park.h5//prediction/0.05 ../Results/Cell_BLAST/Montoro_10x/seurat_genes/dim_10/blast_0/Bach.h5//prediction/0.05 ../Results/Cell_BLAST/Montoro_10x/seurat_genes/dim_10/blast_0/Macosko.h5//prediction/0.05 -o ../Results/Cell_BLAST/Montoro_10x/seurat_genes/dim_10/blast_0/nc.pdf --clean-true --tint-cutoff 5 --width 600 --title "Trachea negative control"
./sankey.py -t ../Datasets/data/Plasschaert/data.h5//obs/cell_ontology_class -p ../Results/Cell_BLAST/Montoro_10x/seurat_genes/dim_10/blast_0/Plasschaert.h5//prediction/0.05 -o ../Results/Cell_BLAST/Montoro_10x/seurat_genes/dim_10/blast_0/pc.pdf --clean-true --tint-cutoff 5 --width 600 --title "Trachea positive control"

./sankey.py -t ../Datasets/data/Baron_mouse/data.h5//obs/cell_ontology_class ../Datasets/data/Park/data.h5//obs/cell_ontology_class ../Datasets/data/Plasschaert/data.h5//obs/cell_ontology_class ../Datasets/data/Macosko/data.h5//obs/cell_ontology_class -p ../Results/Cell_BLAST/Bach/seurat_genes/dim_10/blast_0/Baron_mouse.h5//prediction/0.05 ../Results/Cell_BLAST/Bach/seurat_genes/dim_10/blast_0/Park.h5//prediction/0.05 ../Results/Cell_BLAST/Bach/seurat_genes/dim_10/blast_0/Plasschaert.h5//prediction/0.05 ../Results/Cell_BLAST/Bach/seurat_genes/dim_10/blast_0/Macosko.h5//prediction/0.05 -o ../Results/Cell_BLAST/Bach/seurat_genes/dim_10/blast_0/nc.pdf --clean-true --tint-cutoff 5 --width 600 --title "Mammary negative control"
./sankey.py -t ../Datasets/data/Giraddi_10x/data.h5//obs/cell_ontology_class ../Datasets/data/Quake_Smart-seq2_Mammary_Gland/data.h5//obs/cell_ontology_class ../Datasets/data/Quake_10x_Mammary_Gland/data.h5//obs/cell_ontology_class -p ../Results/Cell_BLAST/Bach/seurat_genes/dim_10/blast_0/Giraddi_10x.h5//prediction/0.05 ../Results/Cell_BLAST/Bach/seurat_genes/dim_10/blast_0/Quake_Smart-seq2_Mammary_Gland.h5//prediction/0.05 ../Results/Cell_BLAST/Bach/seurat_genes/dim_10/blast_0/Quake_10x_Mammary_Gland.h5//prediction/0.05 -o ../Results/Cell_BLAST/Bach/seurat_genes/dim_10/blast_0/pc.pdf --clean-true --tint-cutoff 5 --width 600 --title "Mammary positive control"

./sankey.py -t ../Datasets/data/Baron_mouse/data.h5//obs/cell_ontology_class ../Datasets/data/Park/data.h5//obs/cell_ontology_class ../Datasets/data/Bach/data.h5//obs/cell_ontology_class ../Datasets/data/Plasschaert/data.h5//obs/cell_ontology_class -p ../Results/Cell_BLAST/Quake_10x_Spleen/seurat_genes/dim_10/blast_0/Baron_mouse.h5//prediction/0.05 ../Results/Cell_BLAST/Quake_10x_Spleen/seurat_genes/dim_10/blast_0/Park.h5//prediction/0.05 ../Results/Cell_BLAST/Quake_10x_Spleen/seurat_genes/dim_10/blast_0/Bach.h5//prediction/0.05 ../Results/Cell_BLAST/Quake_10x_Spleen/seurat_genes/dim_10/blast_0/Plasschaert.h5//prediction/0.05 -o ../Results/Cell_BLAST/Quake_10x_Spleen/seurat_genes/dim_10/blast_0/nc.pdf --clean-true --tint-cutoff 5 --width 600 --title "Spleen negative control"
./sankey.py -t ../Datasets/data/Quake_Smart-seq2_Spleen/data.h5//obs/cell_ontology_class -p ../Results/Cell_BLAST/Quake_10x_Spleen/seurat_genes/dim_10/blast_0/Quake_Smart-seq2_Spleen.h5//prediction/0.05 -o ../Results/Cell_BLAST/Quake_10x_Spleen/seurat_genes/dim_10/blast_0/pc.pdf --clean-true --tint-cutoff 5 --width 600 --title "Spleen positive control"

./sankey.py -t ../Datasets/data/Baron_mouse/data.h5//obs/cell_ontology_class ../Datasets/data/Park/data.h5//obs/cell_ontology_class ../Datasets/data/Macosko/data.h5//obs/cell_ontology_class ../Datasets/data/Bach/data.h5//obs/cell_ontology_class -p ../Results/Cell_BLAST/Quake_10x_Lung/seurat_genes/dim_10/blast_0/Baron_mouse.h5//prediction/0.05 ../Results/Cell_BLAST/Quake_10x_Lung/seurat_genes/dim_10/blast_0/Park.h5//prediction/0.05 ../Results/Cell_BLAST/Quake_10x_Lung/seurat_genes/dim_10/blast_0/Macosko.h5//prediction/0.05 ../Results/Cell_BLAST/Quake_10x_Lung/seurat_genes/dim_10/blast_0/Bach.h5//prediction/0.05 -o ../Results/Cell_BLAST/Quake_10x_Lung/seurat_genes/dim_10/blast_0/nc.pdf --clean-true --tint-cutoff 5 --width 600 --title "Lung negative control"
./sankey.py -t ../Datasets/data/Quake_Smart-seq2_Lung/data.h5//obs/cell_ontology_class -p ../Results/Cell_BLAST/Quake_10x_Lung/seurat_genes/dim_10/blast_0/Quake_Smart-seq2_Lung.h5//prediction/0.05 -o ../Results/Cell_BLAST/Quake_10x_Lung/seurat_genes/dim_10/blast_0/pc.pdf --clean-true --tint-cutoff 5 --width 600 --title "Lung positive control"


#===============================================================================
#
#  scmap
#
#===============================================================================
./sankey.py -t ../Datasets/data/Young/data.h5//obs/cell_ontology_class ../Datasets/data/Wu_human/data.h5//obs/cell_ontology_class ../Datasets/data/Zheng_subsample/data.h5//obs/cell_ontology_class ../Datasets/data/Philippeos/data.h5//obs/cell_ontology_class -p ../Results/scmap/Baron_human+Xin_2016+Lawlor/scmap_genes/trial_0/Young.h5//prediction/0.5 ../Results/scmap/Baron_human+Xin_2016+Lawlor/scmap_genes/trial_0/Wu_human.h5//prediction/0.5 ../Results/scmap/Baron_human+Xin_2016+Lawlor/scmap_genes/trial_0/Zheng_subsample.h5//prediction/0.5 ../Results/scmap/Baron_human+Xin_2016+Lawlor/scmap_genes/trial_0/Philippeos.h5//prediction/0.5 -o ../Results/scmap/Baron_human+Xin_2016+Lawlor/scmap_genes/trial_0/nc.pdf --clean-true --tint-cutoff 5 --width 600 --title "Pancreas negative control"
./sankey.py -t ../Datasets/data/Muraro/data.h5//obs/cell_ontology_class ../Datasets/data/Segerstolpe/data.h5//obs/cell_ontology_class ../Datasets/data/Enge/data.h5//obs/cell_ontology_class -p ../Results/scmap/Baron_human+Xin_2016+Lawlor/scmap_genes/trial_0/Muraro.h5//prediction/0.5 ../Results/scmap/Baron_human+Xin_2016+Lawlor/scmap_genes/trial_0/Segerstolpe.h5//prediction/0.5 ../Results/scmap/Baron_human+Xin_2016+Lawlor/scmap_genes/trial_0/Enge.h5//prediction/0.5 -o ../Results/scmap/Baron_human+Xin_2016+Lawlor/scmap_genes/trial_0/pc.pdf --clean-true --tint-cutoff 5 --width 600 --title "Pancreas positive control"

./sankey.py -t ../Datasets/data/Baron_mouse/data.h5//obs/cell_ontology_class ../Datasets/data/Park/data.h5//obs/cell_ontology_class ../Datasets/data/Bach/data.h5//obs/cell_ontology_class ../Datasets/data/Macosko/data.h5//obs/cell_ontology_class -p ../Results/scmap/Montoro_10x/scmap_genes/trial_0/Baron_mouse.h5//prediction/0.5 ../Results/scmap/Montoro_10x/scmap_genes/trial_0/Park.h5//prediction/0.5 ../Results/scmap/Montoro_10x/scmap_genes/trial_0/Bach.h5//prediction/0.5 ../Results/scmap/Montoro_10x/scmap_genes/trial_0/Macosko.h5//prediction/0.5 -o ../Results/scmap/Montoro_10x/scmap_genes/trial_0/nc.pdf --clean-true --tint-cutoff 5 --width 600 --title "Trachea negative control"
./sankey.py -t ../Datasets/data/Plasschaert/data.h5//obs/cell_ontology_class -p ../Results/scmap/Montoro_10x/scmap_genes/trial_0/Plasschaert.h5//prediction/0.5 -o ../Results/scmap/Montoro_10x/scmap_genes/trial_0/pc.pdf --clean-true --tint-cutoff 5 --width 600 --title "Trachea positive control"

./sankey.py -t ../Datasets/data/Baron_mouse/data.h5//obs/cell_ontology_class ../Datasets/data/Park/data.h5//obs/cell_ontology_class ../Datasets/data/Plasschaert/data.h5//obs/cell_ontology_class ../Datasets/data/Macosko/data.h5//obs/cell_ontology_class -p ../Results/scmap/Bach/scmap_genes/trial_0/Baron_mouse.h5//prediction/0.5 ../Results/scmap/Bach/scmap_genes/trial_0/Park.h5//prediction/0.5 ../Results/scmap/Bach/scmap_genes/trial_0/Plasschaert.h5//prediction/0.5 ../Results/scmap/Bach/scmap_genes/trial_0/Macosko.h5//prediction/0.5 -o ../Results/scmap/Bach/scmap_genes/trial_0/nc.pdf --clean-true --tint-cutoff 5 --width 600 --title "Mammary negative control"
./sankey.py -t ../Datasets/data/Giraddi_10x/data.h5//obs/cell_ontology_class ../Datasets/data/Quake_Smart-seq2_Mammary_Gland/data.h5//obs/cell_ontology_class ../Datasets/data/Quake_10x_Mammary_Gland/data.h5//obs/cell_ontology_class -p ../Results/scmap/Bach/scmap_genes/trial_0/Giraddi_10x.h5//prediction/0.5 ../Results/scmap/Bach/scmap_genes/trial_0/Quake_Smart-seq2_Mammary_Gland.h5//prediction/0.5 ../Results/scmap/Bach/scmap_genes/trial_0/Quake_10x_Mammary_Gland.h5//prediction/0.5 -o ../Results/scmap/Bach/scmap_genes/trial_0/pc.pdf --clean-true --tint-cutoff 5 --width 600 --title "Mammary positive control"

./sankey.py -t ../Datasets/data/Baron_mouse/data.h5//obs/cell_ontology_class ../Datasets/data/Park/data.h5//obs/cell_ontology_class ../Datasets/data/Bach/data.h5//obs/cell_ontology_class ../Datasets/data/Plasschaert/data.h5//obs/cell_ontology_class -p ../Results/scmap/Quake_10x_Spleen/scmap_genes/trial_0/Baron_mouse.h5//prediction/0.5 ../Results/scmap/Quake_10x_Spleen/scmap_genes/trial_0/Park.h5//prediction/0.5 ../Results/scmap/Quake_10x_Spleen/scmap_genes/trial_0/Bach.h5//prediction/0.5 ../Results/scmap/Quake_10x_Spleen/scmap_genes/trial_0/Plasschaert.h5//prediction/0.5 -o ../Results/scmap/Quake_10x_Spleen/scmap_genes/trial_0/nc.pdf --clean-true --tint-cutoff 5 --width 600 --title "Spleen negative control"
./sankey.py -t ../Datasets/data/Quake_Smart-seq2_Spleen/data.h5//obs/cell_ontology_class -p ../Results/scmap/Quake_10x_Spleen/scmap_genes/trial_0/Quake_Smart-seq2_Spleen.h5//prediction/0.5 -o ../Results/scmap/Quake_10x_Spleen/scmap_genes/trial_0/pc.pdf --clean-true --tint-cutoff 5 --width 600 --title "Spleen positive control"

./sankey.py -t ../Datasets/data/Baron_mouse/data.h5//obs/cell_ontology_class ../Datasets/data/Park/data.h5//obs/cell_ontology_class ../Datasets/data/Macosko/data.h5//obs/cell_ontology_class ../Datasets/data/Bach/data.h5//obs/cell_ontology_class -p ../Results/scmap/Quake_10x_Lung/scmap_genes/trial_0/Baron_mouse.h5//prediction/0.5 ../Results/scmap/Quake_10x_Lung/scmap_genes/trial_0/Park.h5//prediction/0.5 ../Results/scmap/Quake_10x_Lung/scmap_genes/trial_0/Macosko.h5//prediction/0.5 ../Results/scmap/Quake_10x_Lung/scmap_genes/trial_0/Bach.h5//prediction/0.5 -o ../Results/scmap/Quake_10x_Lung/scmap_genes/trial_0/nc.pdf --clean-true --tint-cutoff 5 --width 600 --title "Lung negative control"
./sankey.py -t ../Datasets/data/Quake_Smart-seq2_Lung/data.h5//obs/cell_ontology_class -p ../Results/scmap/Quake_10x_Lung/scmap_genes/trial_0/Quake_Smart-seq2_Lung.h5//prediction/0.5 -o ../Results/scmap/Quake_10x_Lung/scmap_genes/trial_0/pc.pdf --clean-true --tint-cutoff 5 --width 600 --title "Lung positive control"


#===============================================================================
#
#  CellFishing
#
#===============================================================================
./sankey.py -t ../Datasets/data/Young/data.h5//obs/cell_ontology_class ../Datasets/data/Wu_human/data.h5//obs/cell_ontology_class ../Datasets/data/Zheng_subsample/data.h5//obs/cell_ontology_class ../Datasets/data/Philippeos/data.h5//obs/cell_ontology_class -p ../Results/CellFishing.jl.jl/Baron_human+Xin_2016+Lawlor/cf_genes/trial_0/Young.h5//prediction/110 ../Results/CellFishing.jl/Baron_human+Xin_2016+Lawlor/cf_genes/trial_0/Wu_human.h5//prediction/110 ../Results/CellFishing.jl/Baron_human+Xin_2016+Lawlor/cf_genes/trial_0/Zheng_subsample.h5//prediction/110 ../Results/CellFishing.jl/Baron_human+Xin_2016+Lawlor/cf_genes/trial_0/Philippeos.h5//prediction/110 -o ../Results/CellFishing.jl/Baron_human+Xin_2016+Lawlor/cf_genes/trial_0/nc.pdf --clean-true --tint-cutoff 5 --width 600 --title "Pancreas negative control"
./sankey.py -t ../Datasets/data/Muraro/data.h5//obs/cell_ontology_class ../Datasets/data/Segerstolpe/data.h5//obs/cell_ontology_class ../Datasets/data/Enge/data.h5//obs/cell_ontology_class -p ../Results/CellFishing.jl/Baron_human+Xin_2016+Lawlor/cf_genes/trial_0/Muraro.h5//prediction/110 ../Results/CellFishing.jl/Baron_human+Xin_2016+Lawlor/cf_genes/trial_0/Segerstolpe.h5//prediction/110 ../Results/CellFishing.jl/Baron_human+Xin_2016+Lawlor/cf_genes/trial_0/Enge.h5//prediction/110 -o ../Results/CellFishing.jl/Baron_human+Xin_2016+Lawlor/cf_genes/trial_0/pc.pdf --clean-true --tint-cutoff 5 --width 600 --title "Pancreas positive control"

./sankey.py -t ../Datasets/data/Baron_mouse/data.h5//obs/cell_ontology_class ../Datasets/data/Park/data.h5//obs/cell_ontology_class ../Datasets/data/Bach/data.h5//obs/cell_ontology_class ../Datasets/data/Macosko/data.h5//obs/cell_ontology_class -p ../Results/CellFishing.jl/Montoro_10x/cf_genes/trial_0/Baron_mouse.h5//prediction/110 ../Results/CellFishing.jl/Montoro_10x/cf_genes/trial_0/Park.h5//prediction/110 ../Results/CellFishing.jl/Montoro_10x/cf_genes/trial_0/Bach.h5//prediction/110 ../Results/CellFishing.jl/Montoro_10x/cf_genes/trial_0/Macosko.h5//prediction/110 -o ../Results/CellFishing.jl/Montoro_10x/cf_genes/trial_0/nc.pdf --clean-true --tint-cutoff 5 --width 600 --title "Trachea negative control"
./sankey.py -t ../Datasets/data/Plasschaert/data.h5//obs/cell_ontology_class -p ../Results/CellFishing.jl/Montoro_10x/cf_genes/trial_0/Plasschaert.h5//prediction/110 -o ../Results/CellFishing.jl/Montoro_10x/cf_genes/trial_0/pc.pdf --clean-true --tint-cutoff 5 --width 600 --title "Trachea positive control"

./sankey.py -t ../Datasets/data/Baron_mouse/data.h5//obs/cell_ontology_class ../Datasets/data/Park/data.h5//obs/cell_ontology_class ../Datasets/data/Plasschaert/data.h5//obs/cell_ontology_class ../Datasets/data/Macosko/data.h5//obs/cell_ontology_class -p ../Results/CellFishing.jl/Bach/cf_genes/trial_0/Baron_mouse.h5//prediction/110 ../Results/CellFishing.jl/Bach/cf_genes/trial_0/Park.h5//prediction/110 ../Results/CellFishing.jl/Bach/cf_genes/trial_0/Plasschaert.h5//prediction/110 ../Results/CellFishing.jl/Bach/cf_genes/trial_0/Macosko.h5//prediction/110 -o ../Results/CellFishing.jl/Bach/cf_genes/trial_0/nc.pdf --clean-true --tint-cutoff 5 --width 600 --title "Mammary negative control"
./sankey.py -t ../Datasets/data/Giraddi_10x/data.h5//obs/cell_ontology_class ../Datasets/data/Quake_Smart-seq2_Mammary_Gland/data.h5//obs/cell_ontology_class ../Datasets/data/Quake_10x_Mammary_Gland/data.h5//obs/cell_ontology_class -p ../Results/CellFishing.jl/Bach/cf_genes/trial_0/Giraddi_10x.h5//prediction/110 ../Results/CellFishing.jl/Bach/cf_genes/trial_0/Quake_Smart-seq2_Mammary_Gland.h5//prediction/110 ../Results/CellFishing.jl/Bach/cf_genes/trial_0/Quake_10x_Mammary_Gland.h5//prediction/110 -o ../Results/CellFishing.jl/Bach/cf_genes/trial_0/pc.pdf --clean-true --tint-cutoff 5 --width 600 --title "Mammary positive control"

./sankey.py -t ../Datasets/data/Baron_mouse/data.h5//obs/cell_ontology_class ../Datasets/data/Park/data.h5//obs/cell_ontology_class ../Datasets/data/Bach/data.h5//obs/cell_ontology_class ../Datasets/data/Plasschaert/data.h5//obs/cell_ontology_class -p ../Results/CellFishing.jl/Quake_10x_Spleen/cf_genes/trial_0/Baron_mouse.h5//prediction/110 ../Results/CellFishing.jl/Quake_10x_Spleen/cf_genes/trial_0/Park.h5//prediction/110 ../Results/CellFishing.jl/Quake_10x_Spleen/cf_genes/trial_0/Bach.h5//prediction/110 ../Results/CellFishing.jl/Quake_10x_Spleen/cf_genes/trial_0/Plasschaert.h5//prediction/110 -o ../Results/CellFishing.jl/Quake_10x_Spleen/cf_genes/trial_0/nc.pdf --clean-true --tint-cutoff 5 --width 600 --title "Spleen negative control"
./sankey.py -t ../Datasets/data/Quake_Smart-seq2_Spleen/data.h5//obs/cell_ontology_class -p ../Results/CellFishing.jl/Quake_10x_Spleen/cf_genes/trial_0/Quake_Smart-seq2_Spleen.h5//prediction/110 -o ../Results/CellFishing.jl/Quake_10x_Spleen/cf_genes/trial_0/pc.pdf --clean-true --tint-cutoff 5 --width 600 --title "Spleen positive control"

./sankey.py -t ../Datasets/data/Baron_mouse/data.h5//obs/cell_ontology_class ../Datasets/data/Park/data.h5//obs/cell_ontology_class ../Datasets/data/Macosko/data.h5//obs/cell_ontology_class ../Datasets/data/Bach/data.h5//obs/cell_ontology_class -p ../Results/CellFishing.jl/Quake_10x_Lung/cf_genes/trial_0/Baron_mouse.h5//prediction/110 ../Results/CellFishing.jl/Quake_10x_Lung/cf_genes/trial_0/Park.h5//prediction/110 ../Results/CellFishing.jl/Quake_10x_Lung/cf_genes/trial_0/Macosko.h5//prediction/110 ../Results/CellFishing.jl/Quake_10x_Lung/cf_genes/trial_0/Bach.h5//prediction/110 -o ../Results/CellFishing.jl/Quake_10x_Lung/cf_genes/trial_0/nc.pdf --clean-true --tint-cutoff 5 --width 600 --title "Lung negative control"
./sankey.py -t ../Datasets/data/Quake_Smart-seq2_Lung/data.h5//obs/cell_ontology_class -p ../Results/CellFishing.jl/Quake_10x_Lung/cf_genes/trial_0/Quake_Smart-seq2_Lung.h5//prediction/110 -o ../Results/CellFishing.jl/Quake_10x_Lung/cf_genes/trial_0/pc.pdf --clean-true --tint-cutoff 5 --width 600 --title "Lung positive control"