rule case_study:
    input:
        "Trachea/trachea_case_study.html",
        "HSC/hsc_case_study.html"
    output:
        ".case_study_timestamp"
    threads: 1
    shell:
        "touch {output}"

rule trachea_case_study:
    input:
        "Trachea/trachea_case_study.ipynb"
    output:
        "Trachea/trachea_case_study.html"
    log:
        "Trachea/trachea_case_study.log"
    threads: 4
    resources:
        gpu=1
    shell:
        "cd Trachea && jupyter nbconvert --to html "
        "--ExecutePreprocessor.timeout=3600000 --allow-errors "
        "--execute trachea_case_study.ipynb "
        "--output trachea_case_study.html "
        "> trachea_case_study.log 2>&1"

rule hsc_case_study:
    input:
        "HSC/hsc_case_study.ipynb"
    output:
        "HSC/hsc_case_study.html"
    log:
        "HSC/hsc_case_study.log"
    threads: 4
    resources:
        gpu=1
    shell:
        "cd HSC && jupyter nbconvert --to html "
        "--ExecutePreprocessor.timeout=3600000 --allow-errors "
        "--execute hsc_case_study.ipynb "
        "--output hsc_case_study.html "
        "> hsc_case_study.log 2>&1"